version: "3"
services:
  wallpaper_server:
    build:
      context: .
      dockerfile: ./dockerfile
    image: midjourney-wallpaper-server
    ports:
      - 8080:8080
    networks:
      - mj_hub
    volumes:
      - ../mj_walls:/app/wallpapers
      - .:/app/env
      - ../midjourney-wallpaper-ui/build:/app/static_web

    depends_on:
      - redis

  wallpaper_scraper:
    build:
      context: ../midjourney-scraper
      dockerfile: ../midjourney-scraper/dockerfile
    image: midjourney-wallpaper-scraper
    networks:
      - mj_hub
    volumes:
      - ../mj_walls:/app/wallpapers
      - ../midjourney-scraper:/app/env

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - mj_hub

volumes:
  redis:
    driver: local

networks:
  mj_hub:
    driver: bridge
