version: "3"
services:
  wallpaper_server:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../mj_wallpaperiser/data:/app/data
    links:
      - redis
    depends_on:
      - redis
    container_name: mj_slideshow

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
